### ISSUE TITLE
Logging Settings

### ISSUE THREAD

**Issue by ccoffrin** [Wikunia/MINLPBnB#27]
There should be a setting for controlling how much terminal logging occurs.  With a value of `0` meaning silent, and the default value being the amount of logging that currently happens.

The setting should be set to silent during `runtests.jl`.

**Comment by Wikunia** [comment]
I'm usually not a huge fan of an integer log level ;)
I'm using a symbol based option atm:
So the user can specify the output in a more direct way like: `log_levels = [:Table,:Info,:Timing]`
If that array is empty there is no output at all besides output from Ipopt like `Infeasible` warning in between. Still figuring out how to suppress those.

**Comment by ccoffrin** [comment]
Integers are typical, but I agree not ideal.  If you prefer symbols that's fine by me.
