### ISSUE TITLE
Solve Statistics

### ISSUE THREAD

**Issue by ccoffrin** [Wikunia/MINLPBnB#29]
We need methods to get info about the the solve.  For example, 

- number of nodes explored
- number of cuts generated

The [gurobi docs](http://www.gurobi.com/documentation/7.5/refman/attributes.html) can provide some inspiration.

**Comment by Wikunia** [comment]
Just to clarify:

The number of explored nodes is the number of computed relaxations, right?
- Includes the number of relaxations computed during a strong branching step

The number of cuts generated is at the moment the number of new incumbent solution and therefore the number of bounding steps, right?

**Comment by ccoffrin** [comment]
The number of explored noted is actually the size of the tree that was explored.  How strong branching effects this depends on the implementation.

If you throw out all the information after doing strong branching this would only count as 1 node.  If you are opening a bunch of new nodes and then branching on the best one first, then it would count as multiple nodes.

**Comment by ccoffrin** [comment]
Regarding number of cuts generated, probably the number of constraints added to the problem during search is the right number.

**Comment by Wikunia** [comment]
In strong branching I branch on different variables (each creating two nodes) then choose the best for the tree. I only store the information of the gain for future branching like pseudo cost.
