### ISSUE TITLE
Using getobjbound()

### ISSUE THREAD

**Issue by ccoffrin** [Wikunia/MINLPBnB#43]
It seems if the problem solved at the root node this returns `NaN`.  Also when the search is finished the `getobjbound` is still lower than `getobjectivevalue`.  Once you have searched all of the nodes both of these values should coverage to the same thing.

**Comment by Wikunia** [comment]
Yeah atm I'm computing the bound before each step and might break before. After the loop finished I should update the bound again.

**Comment by Wikunia** [comment]
Okay Ipopt responds has a best bound of `0`. I don't know whether it's more reasonable than `NaN`?
So the `bound` should equal the `objective` if there are no open nodes and otherwise be the min of all open nodes if minimizing and the max of all open nodes if maximizing right?

**Comment by ccoffrin** [comment]
That is correct.
