### ISSUE TITLE
Throw warning or Error? if option doesn't exist

### ISSUE THREAD

**Issue by Wikunia** [Wikunia/MINLPBnB#60]

**Comment by ccoffrin** [comment]
A warning is the standard.

**Comment by Wikunia** [comment]
And an error if a `branching_strategy` doesn't exist? Which will produce an error eventually anyway somewhere...

**Comment by ccoffrin** [comment]
Other solvers throw a warning when an option is not recognized and an error if a recognized option has an incorrect value.
